install.packages('tidyverse', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(tidyverse, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('plotly', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(plotly, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('patchwork', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(patchwork, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('argparser', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(argparser, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('arrow', dependencies=TRUE, repos='https://cloud.r-project.org')
if (!library(arrow, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('jsonlite', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(jsonlite, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('wesanderson', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(wesanderson, logical.return=T)) quit(save='no', status=10, runLast=F)
install.packages('latex2exp', dependencies=TRUE, repos='http://cran.rstudio.com/')
if (!library(latex2exp, logical.return=T)) quit(save='no', status=10, runLast=F)
