#docker run --rm -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro -v $(pwd)/simulations:/app/simulations:ro -v $(pwd)/sim_data:/app/sim_data -v $(pwd)/core/equations/:/app/core/equations/:ro -v $(pwd)/core/utils/:/app/core/utils/:ro -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro pabloabur/app --save_path sim_data/stdp_test/ STDP --protocol 1 --event_condition "abs(Ca) > 0.02"
#docker run --rm -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro -v $(pwd)/simulations:/app/simulations:ro -v $(pwd)/sim_data:/app/sim_data -v $(pwd)/core/equations/:/app/core/equations/:ro -v $(pwd)/core/utils/:/app/core/utils/:ro -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro pabloabur/app --save_path sim_data/stdp_test/kernel_sim/ STDP --protocol 2 --event_condition "abs(Ca) > 0.02"
#docker run --entrypoint /bin/bash -it --rm -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro -v $(pwd)/simulations:/app/simulations:ro -v $(pwd)/sim_data:/app/sim_data -v $(pwd)/core/equations/:/app/core/equations/:ro -v $(pwd)/core/utils/:/app/core/utils/:ro -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro pabloabur/app -c "echo 'b simulations/stdp.py:306\nc' > ~/.pdbrc && micromamba run -n base -r /opt/micromamba python -m pdb run_simulation.py STDP --protocol 3 --event_condition 'abs(Ca) > 0.02'"
#nposts=(1 10 100)
#for trials in {0..9}; do
#    for npost in "${nposts[@]}"; do
#        docker run --rm -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro -v $(pwd)/simulations:/app/simulations:ro -v $(pwd)/sim_data:/app/sim_data -v $(pwd)/core/equations/:/app/core/equations/:ro -v $(pwd)/core/utils/:/app/core/utils/:ro -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro pabloabur/app --save_path sim_data/stdp_test/$(date +"%d-%m_%Hh%Mm%Ss") --quiet STDP --protocol 3 --w_max 0.4 --event_condition "abs(Ca) > 0.02" --tmax 5000 --N_post $npost
#    done
#done
#docker run --rm -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro -v $(pwd)/simulations:/app/simulations:ro -v $(pwd)/sim_data:/app/sim_data -v $(pwd)/core/equations/:/app/core/equations/:ro -v $(pwd)/core/utils/:/app/core/utils/:ro -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro pabloabur/app --save_path sim_data/stdp_test/ STDP --event_condition "Ca > 0" --protocol 1 --precision 'fp8'
docker run --entrypoint /bin/bash -it --rm -v $(pwd)/run_simulation.py:/app/run_simulation.py:ro -v $(pwd)/simulations:/app/simulations:ro -v $(pwd)/sim_data:/app/sim_data -v $(pwd)/core/equations/:/app/core/equations/:ro -v $(pwd)/core/utils/:/app/core/utils/:ro pabloabur/app -c "echo 'b core/utils/misc.py:971' > ~/.pdbrc && micromamba run -n base -r /opt/micromamba python -m pdb run_simulation.py STDP --protocol 1 --precision 'fp8'"
